# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

parameters:
            - name: projectName
              displayName: projectName?
              type: string

stages:
  - stage: UserInput
    jobs:
      - job: 'UserInputProjectName'
        pool:
          vmimage: windows-latest
        
        steps:
           - task: PowerShell@2
             inputs:
               targetType: 'inline'
               script: |
                 $variable = '${{parameters.projectName}}'
                 $variable | Out-File $(Build.ArtifactStagingDirectory)\projectName.txt
                 Get-Content $(Build.ArtifactStagingDirectory)\projectName.txt

           - task: ManualIntervention@8
             inputs:
              instructions: 'ProjectName'
           
